version: '3.8'

services:
  # PostgreSQL Database (with migrations and seeders)
  db:
    image: postgres:15
    container_name: nourishnet_db
    environment:
      POSTGRES_DB: nourishnet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API (Node.js, hot reload with nodemon)
  backend:
    build: 
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: nourishnet_backend
    environment:
      - NODE_ENV=development
      - PORT=5000
      - CORS_ORIGIN=http://localhost:3000
    ports:
      - "5000:5000"
    volumes:
      - ./docs/openapi.yaml:/docs/openapi.yaml
    depends_on:
      db:
        condition: service_healthy
    command: npm run dev
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React App (hot reload with Vite)
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: nourishnet_frontend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm start
    stdin_open: true
    tty: true

  # Redis for session management and caching (optional)
  redis:
    image: redis:7-alpine
    container_name: nourishnet_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Adminer for database management (development only)
  adminer:
    image: adminer:latest
    container_name: nourishnet_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: nourishnet_network
